# Generated by Django 5.0.4 on 2024-08-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_mascota_vacunado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='mascota',
        ),
        migrations.AddField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_mascotas/'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos_mascotas/'),
        ),
        migrations.DeleteModel(
            name='Foto',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
